# Generated by Django 6.0.7 on 2026-07-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.PositiveIntegerField(help_text='Mileage in miles or km')),
                ('transmission', models.CharField(choices=[('a', 'Automatic'), ('m', 'Manual'), ('c', 'CVT')], default='a', max_length=2)),
                ('fuel_type', models.CharField(choices=[('g', 'Gasoline'), ('d', 'Diesel'), ('e', 'Electric'), ('h', 'Hybrid')], default='g', max_length=2)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='cars/%Y/%m/%d')),
                ('stock', models.PositiveIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='store.brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='store.category')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='store_car_created_933144_idx')],
            },
        ),
    ]
